### ISSUE TITLE
CSXCAD not found when running example "python3 patch_antenna/create_patch.py"

### ISSUE THREAD

**Issue by marcelgln** [oskarvh/kicad_openems_pipeline#1]
This project looks like a good starting point for using openEMS, thanks :-)

Probably it's my limited Python knowledge. As far as I know I performed the required install steps (WSL2/Ubuntu) . 
but when trying to run the example Python doe not find CSXCAD. 

    import CSXCAD
ModuleNotFoundError: No module named 'CSXCAD'

Is there a step that I overlooked ?

**Comment by marcelgln** [comment]
Turned out the install from openEMS was a bit misleading. It ended with "installed succesfully" while a few lines  above some some errors related to Python appeared.  This was related to setuptools and packaging. Finally was able to run the patch antenna example.

**Comment by oskarvh** [comment]
Thanks! 
Good to hear that you got it working! 
Note that this is a (slow) work in progress, I never got the simulation setup to really work but the pipeline should at least do its job. 

Closing this ticket now, feel free to open a new one if you have more questions :)
